l_english:
 SETTING_HINTS:0 "ヒント"
 SETTING_LAST_HOST:0 "最後のホスト"
 SETTING_LAST_PLAYER:0 "最後のプレイヤー"
 SETTING_DIFFICULTY:0 "難易度"
 SETTING_AUTOSAVE:0 "オートセーブの間隔"
 SETTING_DEBUG_SAVES:0 "デバッグセーブの数"
 SETTING_WINDOW_MOVE_TIME:0 "ウィンドウ移動時間"
 SETTING_RADIAL_STAY_TIME:0 "Radial stay time"
 SETTING_CAMERA_FACE_NORTH:0 "カメラが北を向く"
 SETTING_AUTOSAVE_TO_CLOUD:0 "クラウドに自動保存する"
 SETTING_DISABLED_ALERTS:0 "警告を無効化"
 SETTING_DISABLED_HINTS:0 "ヒントを無効化"
 SETTING_FOCUS_ON_COMBAT:0 "戦闘にフォーカスする"
 SETTING_PROVINCE_NAMES:0 "州の名前"
 SETTING_MAX_TICKS_AHEAD:0 "Max ticks ahead"
 MAPNAME_MODE_ALWAYS_ON:0 "常にオン"
 MAPNAME_MODE_ALWAYS_OFF:0 "常にオフ"
 MAPNAME_MODE_MOUSE_OVER:0 "マウスオーバー"
 MAPNAME_MODE_DEFAULT:0 "デフォルト"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN:0 "通行不可な地形を埋める"
 SETTING_DRAW_TERRAIN:0 "地形を描写する"
 SETTING_DRAW_WATER:0 "水を描写する"
 SETTING_DRAW_BORDERS:0 "国境を表示する"
 SETTING_DRAW_TREES:0 "木を描写する"
 SETTING_DRAW_RIVERS:0 "川を描写する"
 SETTING_DRAW_POSTFX:0 "postfxを描写する"
 SETTING_DRAW_SKY:0 "空を描写する"
 SETTING_DRAW_BLOOM:0 "ブルームを描写する"
 SETTING_DRAW_TOOLTIPS:0 "ツールチップを表示する"
 SETTING_DRAW_CITYSPRAWL:0 "都市の拡がりを描写する"
 SETTING_DRAW_SHADOWS:0 "影を描写する"
 SETTING_OUTLINER_SHOW_OUTLINER:0 "アウトライナーを表示する"
 SETTING_OUTLINER_PLAYER_ARMIES:0 "プレイヤーの陸軍を表示する"
 SETTING_OUTLINER_PLAYER_NAVIES:0 "プレイヤーの海軍を表示する"
 SETTING_OUTLINER_AUTOMATED_NAVIES:0 "プレイヤーの海軍を表示する"
 SETTING_OUTLINER_AUTOMATED_ARMIES:0 "プレイヤーの海軍を表示する"
 SETTING_OUTLINER_PROVINCIAL_ARMIES:0 "プレイヤーの海軍を表示する"
 SETTING_OUTLINER_COMBATS:0 "戦闘を表示する"
 SETTING_OUTLINER_SIEGES_OUR:0 "我々が包囲中の都市を表示する"
 SETTING_OUTLINER_SIEGES_HOSTILE:0 "敵が包囲中の都市を表示する"
 SETTING_OUTLINER_DISLOYAL_CHARACTERS:0 "不忠な人物を表示する"
 SETTING_OUTLINER_CONSTRUCTIONS_BUILDINGS:0 "建設を表示する"
 SETTING_OUTLINER_CONSTRUCTIONS_MILITARY:0 "軍事建設を表示する"
 SETTING_OUTLINER_ACTIVE_WARS:0 "継続中の戦争を表示する"
 SETTING_OUTLINER_ACTIVE_DIPLOMACY:0 "継続中の外交を表示する"
 SETTING_OUTLINER_HUMAN_PLAYERS:0 "人間のプレイヤーを表示する"
 SETTING_FOCUS_ON_COMBAT_TOOLTIP:0 "戦闘を観察しているときにゲーム速度を制限するかどうかを設定します。"
 SETTING_PAUSE_ON_EVENTS:0 "イベント発生時に一時停止する"
 SETTING_OUTLINER_PROVINCEMODIFIER:0 "区域の改善を表示する"
 SETTING_ADVICE:0 "Advice on alert"
 SETTING_ADVICE_TOOLTIP:0 "Determines if advice and highlights will be shown when clicking an alert icon"