l_english:
 difficulty_very_easy_tooltip:1 "難易度：#Y 非常に簡単#!\n\n最も易しいゲーム難度。プレイヤーは大幅な強化を受け、AI国家にはペナルティが与えられます。\nまた、プレイヤーに対するAIの好戦性が弱まります。\n\n#T プレイヤー補正：#!\n$PLAYER_MODIFIERS$\n#T AI補正：#!\n$AI_MODIFIERS$"
 difficulty_easy_tooltip:1 "難易度：#Y 簡単#!\n\nより穏やかで平易なプレイを経験することができるゲーム難度。プレイヤーにはボーナスが与えられます。\n「普通」以上の難易度を選択した場合よりも、プレイヤーに対するAIの好戦性が抑えらます。\n\n#T プレイヤー補正：#!\n$PLAYER_MODIFIERS$\n#T AI補正：#!\n$AI_MODIFIERS$"
 difficulty_normal_tooltip:1 "難易度：#Y 普通#!\n\nバランスの取れたゲーム難度。プレイヤー、AIともにいかなるボーナスも与えられません。\nAIは、プレイヤー・AI国家を同等に扱います。\n\n#T プレイヤー補正：#!\n$PLAYER_MODIFIERS$\n#T AI補正：#!\n$AI_MODIFIERS$"
 difficulty_hard_tooltip:1 "難易度：#Y 難しい#!\n\nより経験を積んだプレイヤーのためのゲーム難度。\nAI国家にのみボーナスが与えられ、AIの行動がより好戦的になります。\n\n#T プレイヤー補正：#!\n$PLAYER_MODIFIERS$\n#T AI補正：#!\n$AI_MODIFIERS$"
 difficulty_very_hard_tooltip:1 "難易度：#Y 非常に難しい#!\n\n最も難しいゲーム難度。AIには大幅なボーナスが与えられ、プレイヤーが受けるボーナスはありません。\nAI国家はさらに好戦的になります。\n\n#T プレイヤー補正：#!\n$PLAYER_MODIFIERS$\n#T AI補正：#!\n$AI_MODIFIERS$"
 DIFFICULTY_TOOLTIP:1 "難易度：\nAIの振舞いを変更したり国家を強化することにより、ゲームの難しさを調整できます。"
 IRONMAN_TOOLTIP:2 "#Y 鉄人モード#!：\n\nより挑戦的なゲームモードを楽しめます。\n- #T MODを使用していなければ実績解除可能#!\n- ゲームごとにセーブファイルを一つに制限\n- 非選択式で頻繁なオートセーブ\n- コンソール使用不可\n- プレイ国家の変更不可"
 IRONMAN_DISABLED_NOT_SIGNED_TOOLTIP:1 "#Y 鉄人モード#!を有効にしてプレイするには\nParadoxアカウントにサインインしてください：\n\nより挑戦的なゲームモードを楽しめます。\n- #T MODを使用していなければ実績解除可能#!\n- ゲームごとにセーブファイルを一つに制限\n- 非選択式で頻繁なオートセーブ\n- コンソール使用不可\n- プレイ国家の変更不可"
 IRONMAN_DISABLED_MP_TOOLTIP:1 "#Y 鉄人モード#!はマルチプレイヤーモードでは利用できません：\n\nより挑戦的なゲームモードを楽しめます。\n- #T MODを使用していなければ実績解除可能#!\n- ゲームごとにセーブファイルを一つに制限\n- 非選択式で頻繁なオートセーブ\n- コンソール使用不可\n- プレイ国家の変更不可"
 SETTING_HEADER:0 "設定"
 AI_SETTINGS:0 "AI設定"
 AI_SETTING0:0 "戦争の許可"
 AI_SETTING1:0 "参戦要請への返答"
 AI_SETTING2:0 "条約の遵守"
 AI_SETTING3:0 "予算の管理"
 AI_SETTING4:0 "交易の管理"
 AI_SETTING5:0 "指揮官の配属"
 AI_SETTING6:0 "役職の配属"
 AI_SETTING7:0 "決断の実行"
 AI_SETTING8:0 "早期の和平"
 AI_SETTING9:0 "発明の取得"
 AI_SETTING10:0 "ユニットの解散"
 AI_SETTING11:0 "軍の伝統の取得"
 AI_SETTING12:0 "統治政策の変更"
 AI_SETTING13:0 "建造物の建設"
 AI_SETTING14:0 "建造物の破壊"
 AI_SETTING_TT0:0 "AIが新たな戦争を開始することを許可または禁止します。"
 AI_SETTING_TT1:0 "チェックを外した場合、我々に対する同盟国の参戦要請は自動的に拒絶されます。"
 AI_SETTING_TT2:0 "チェックした場合、AIは可能な限り新たな外交関係を結んだり、すでに存在する外交関係を破棄したりしません。"
 AI_SETTING_TT3:0 "AIが経済政策を変更することを許可または禁止します。"
 AI_SETTING_TT4:0 "AIが交易路を変更することを許可または禁止します。"
 AI_SETTING_TT5:0 "AIが指揮官を配属したり、すでに配属されている指揮官を解任することを許可または禁止します。"
 AI_SETTING_TT6:0 "AIが人物を役職に任命しなおすことを許可または禁止します。"
 AI_SETTING_TT7:0 "AIが決断を実行することを許可または禁止します。"
 AI_SETTING_TT8:0 "チェックした場合、AIは何とかして戦争の和平を可能な限り早期に結ぼうと試みます。"
 AI_SETTING_TT9:0 "AIが発明を取得することを許可または禁止します。"
 AI_SETTING_TT10:0 "より経済的であると判断した場合に、AIが部隊を解散することを許可または禁止します。"
 AI_SETTING_TT11:0 "AIが軍の伝統を取得することを許可または禁止します。"
 AI_SETTING_TT12:0 "AIが統治政策を変更することを許可または禁止します。"
 AI_SETTING_TT13:0 "AIが建造物を建設することを許可または禁止します。"
 AI_SETTING_TT14:0 "その場所により有益な建造物を建てられると判断した時や、要塞が経済的負担となっている場合に、AIが建造物を破壊することを許可または禁止します。"
 IRONMAN_MODS_ENABLED_TOOLTIP:0 "#Y 鉄人モード#!：\n\n#N （MODを使用して鉄人モードを開始すると実績が解除できません）#!\n\nより挑戦的なゲームモードを楽しめます。\n- #T MODを使用していなければ実績解除可能#!\n- ゲームごとにセーブファイルを一つに制限\n- 非選択式で頻繁なオートセーブ\n- コンソール使用不可\n- プレイ国家の変更不可"